server:
    port: 5432

spring:
    datasource:
        url: jdbc:postgresql://dpg-cpf3n2lds78s7395nid0-a.oregon-postgres.render.com/postgres_zs5k?user=postgres_zs5k_user&password=xVEqJlVMYDF9t5VYbqmGCivNW0w2vdTF
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa:
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            schema-locations: classpath:schema-postgresql.sql
            mode: always
            platform: postgres

logging:
    level:
        root: INFO
        org.springframework: DEBUG
        org.hibernate: DEBUG